name: FastChat Intel GPU
slug: fastchat-arc
description: Run FastChat with Intel Arc/iGPU (OpenAI API + Web UI)
startup: application
ingress: true
panel_icon: mdi:robot
panel_title: FastChat
arch:
  - amd64

image: "ghcr.io/martinwierenga/fastchat-intel-gpu:latest"
version: "latest"    # or "1.0.2" if you tagged it


options:
  model_path: "/share/models/naturalfunctions"
  max_gpu_memory: "8Gib"
  log_path: "/share/fastchat/logs"
  log_level: "debug"


schema:
  model_path: str
  max_gpu_memory: str
  log_level: list(info|warning|error|debug)
  log_path: str
