name: "FastChat Arc"
version: "latest"
slug: "fastchat_arc"
description: "FastChat with Intel GPU support and Hugging Face model download."
arch:
  - amd64
startup: services
boot: auto
options:
  model_path: "/share/models/mistral-7b-instruct"
  max_gpu_memory: "8Gib"
  log_level: "debug"
  log_path: "/share/fastchat/logs"
  hf_token: <YOUR_HUGGING_FACE_TOKEN>
schema:
  model_path: str
  max_gpu_memory: str
  log_level: list(debug|info|warning|error)
  log_path: str
  hf_token: password