name: FastChat Intel GPU
version: "latest"
slug: fastchat-arc
description: Run FastChat with Intel Arc/iGPU (OpenAI API + Web UI)
startup: application
ingress: true
panel_icon: mdi:robot
panel_title: FastChat
arch:
  - amd64

image: "ghcr.io/martinwierenga/fastchat-intel-gpu"

options:
  model_path: "/share/models/naturalfunctions"
  max_gpu_memory: "8Gib"
  log_level: "debug"
  log_path: "/share/fastchat/logs"

schema:
  model_path: str
  max_gpu_memory: str
  log_level: list(info|warning|error|debug)
  log_path: str
