name: "FastChat Arc"
version: "latest"
slug: "fastchat_arc"
description: "Serve FastChat with Intel GPU (Arc/iGPU) on Home Assistant OS"
url: "https://github.com/martinwierenga/hassio-addons"
arch:
  - amd64
startup: services
init: false
host_network: true

# Allow GPU and volume access
privileged:
  - SYS_ADMIN

map:
  - share:rw

options:
  model_path: "/share/models/mistral-7b-instruct"
  max_gpu_memory: "8Gib"
  log_level: "debug"
  log_path: "/share/fastchat/logs"

schema:
  model_path: str
  max_gpu_memory: str
  log_level: list(debug|info|warning|error)
  log_path: str

panel_icon: "mdi:robot"
panel_title: "FastChat"
panel_admin: false
ingress: false
