name: Llama Intel Arc Docker
version: 1.0.0
slug: llamadockerintelarc
description: Docker container for running Llama models with Intel Arc GPU support.
maintainer: Martin Wierenga
url: https://github.com/MartinWierenga/hassio-addons
codenotary: martinwierenga@live.nl
arch:
  - amd64
startup: services
boot: auto
init: false
map:
  - media:rw
  - share:rw
  - addon_config:rw
ports:
  7860/tcp: 7860
  8000/tcp: 8000
ports_description:
  7860/tcp: API interface (Not required for Ingress)
  8000/tcp: Web interface (Not required for Ingress)

environment:
  LOG_FORMAT: "{LEVEL}: {MESSAGE}"