name: Llama Intel Arc Docker
version: 1.0.0
slug: llamadockerintelarc
description: Docker container for running Llama models with Intel Arc GPU support.
maintainer: Martin Wierenga
url: https://github.com/MartinWierenga/hassio-addons
codenotary: martinwierenga@live.nl
arch:
  - amd64
startup: services
boot: auto
init: false