name: Llama Intel Arc Docker
version: 1.0.0
slug: llamadockerintelarc
description: Docker container for running Llama models with Intel Arc GPU support.
maintainer: Martin Wierenga
url: https://github.com/MartinWierenga/hassio-addons
codenotary: martinwierenga@live.nl
arch:
  - amd64
startup: services
boot: auto
port:
  - 8000/tcp
map:
  - media/models
full_access: true
supervisor_api: true
homeassistant: 2025.6.0
backup: hot
