name: Studio Code Server Checker
version: 1.0.0
slug: studiocodecheck
description: Monitor your Studio Code Server add-on and send a repair notification when it shows memory or CPU leaks. Optionally auto restart the container and track historical CPU and memory usage.
url: https://github.com/MartinWierenga/hassio-addons/tree/main/studiocodecheck
codenotary: martinwierenga@live.nl
arch:
  - armv7
  - aarch64
  - amd64
startup: application
boot: auto
init: false
hassio_api: true
hassio_role: admin
host_network: true
options:
  cpu_threshold: 5
  mem_threshold: 5
  check_interval: 60
  failure_count: 3
  container_name: addon_a0d7b954_vscode
  use_mqtt_logging: false
  log_file_max_bytes: 1048576
  log_file_backup_count: 3
  mqtt_broker: 
  mqtt_port: 1883
  mqtt_topic: homeassistant/studio_code_logs
  mqtt_username: 
  mqtt_password: 
  enable_auto_restart: true
  enable_notifications: false
  healthcheck_port: 8080
  notification_title: Studio Code Server Checker Repair
  homeassistant_url: http://supervisor/core
  enable_historical_tracking: true
  historical_tracking_file: /data/historical_usage.csv
schema:
  cpu_threshold: int
  mem_threshold: int
  check_interval: int
  failure_count: int
  container_name: str
  use_mqtt_logging: bool
  log_file_max_bytes: int
  log_file_backup_count: int
  mqtt_broker: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_username: str
  mqtt_password: str
  enable_auto_restart: bool
  enable_notifications: bool
  healthcheck_port: int
  notification_title: str
  homeassistant_url: str
  enable_historical_tracking: bool
  historical_tracking_file: str
services:
  - mqtt:want
udev: true
full_access: true
homeassistant: 2025.4.0
backup: hot
auth_api: true
homeassistant_api: true
docker_api: true
devices:
  - /var/run/docker.sock:/var/run/docker.sock:rw