name: Studio Code Server Checker
version: 1.0.0
slug: studiocodecheck
description: Monitor your Studio Code Server add-on and send a repair notification when it shows memory or CPU leaks. Optionally auto restart the container and track historical CPU and memory usage.
url: https://github.com/MartinWierenga/hassio-addons/tree/main/studiocodecheck
codenotary: martinwierenga@live.nl
arch:
  - armv7
  - aarch64
  - amd64
startup: application
boot: auto
init: false
hassio_api: true
hassio_role: admin
host_network: true
options:
  monitor_containers:
    - addon1
    - addon2
schema:
  monitor_containers:
    description: List of add-ons to monitor for CPU and memory leaks.
    default: []
    required: true
map:
  - /var/run/docker.sock: /var/run/docker.sock
  - /data: /data
services:
  - mqtt:want
udev: true
full_access: true
homeassistant: 2025.4.0
backup: hot
auth_api: true
homeassistant_api: true
docker_api: true