name: Build & Push FastChat Intel GPU

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'run.sh'
      - '.github/workflows/build-fastchat.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag name
        id: vars
        run: |
          TAG=${GITHUB_REF##*/}
          USERNAME=${GITHUB_REPOSITORY_OWNER,,}
          IMAGE_NAME=ghcr.io/$USERNAME/fastchat-intel-gpu
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fastchat-arc
          file: ./fastchat-arc/Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}
            ${{ steps.vars.outputs.image }}:latest
